### ISSUE TITLE
Feature Request: Glucose Listen Only

### ISSUE THREAD

**Issue by juehv** [xdrip-js/Logger#142]
As discussed in Gitter with @efidoman, here is my feature request:

I use a G6 but I guess it's the technically the same as for G5. I'd like to use Logger just for listening to the transmitted glucose values. Everything else (calibration, sensor-start, sensor-stop, error management, etc) I want to handle with the app or the Dexcom reader. As I understood the documentation, Logger needs to send a sensor start command to the transmitter to listen to glucose values. I'm worried multiple start commands could cause issues with the auto calibration. However, even if not I guess it would be better to not send unnecessary commands if I just want the glucose values.

Cheers!

**Comment by efidoman** [comment]
We could add a listen only mode flag to Logger. For g6 in no calibration mode, calibration values are not required. However, Logger does require the calibration values otherwise to calculate the glucose value based on the analog unfiltered / filtered values from the sensor. Also, Logger requires calibration data for expired mode. @juehv  - does your Nightscout show a treatment record when you calibrate via the receiver? Wondering if that could be a way for Logger to get the calibration record when it is done via the receiver?

**Comment by efidoman** [comment]
I just tried calibrating via my g6 receiver and it didn't show up in Nightscout, so we would need to figure out how to get the calibration record from the receiver to Logger or just allow this read only mode in non-expired mode only. Thoughts?

**Comment by juehv** [comment]
Well, I don't want to rely on nightscout because I'm quite often offline. I designed my current (enlite based) loop to work without internet connection. I use nightscout just  for reporting. I would be happy with no calibration mode only, since I actually want the dexcom calculated values.

I guess if someone really wants to use expired sensors and the listen only mode at the same time, one could use xdrip on the phone or the existing commandline tool to calibrate.

**Comment by efidoman** [comment]
Good points - we can consider a listen only mode with those assumptions. 
Are you using enlite sensors or Dexcom? Logger only works with Dexcom.

**Comment by juehv** [comment]
I currently use Enlite but I'll switch to Dexcom G6 next month :)

**Comment by efidoman** [comment]
This feature was added to Logger.

**Comment by juehv** [comment]
Thanks! Is there some documentation how to use it? Cheers!
